# Use Go 1.24
FROM golang:1.24

WORKDIR /app

# Install Air for hot reload
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the app
COPY . .

# Set Air as the entrypoint
CMD ["air"]
